### ISSUE TITLE
appveyor.yml contains Nuget API Key

### ISSUE THREAD

**Issue by jbattermann** [forcewake/HyperPropertyDescriptor#2]
Hey there,

I was just reading Marc's original CodeProject article about HyperDescriptor and was looking for an 'official' NuGet package.. and then any non-official of that matter as Marc apparently never published it as a NuGet package.. when I saw yours, but saw that your appveyor.yml appears to contain your NuGet API key (see https://github.com/forcewake/HyperPropertyDescriptor/blob/master/appveyor.yml#L31) ... which, if it's still the same, might be somewhat of a risky thing to have under publicly viewable source-control.

I.e. one could clone your repo, modify the code slightly to do "horrible" things and publish a new version of the package :-/

Just as a heads-up..

Cheers,
-J

**Comment by forcewake** [comment]
Thank you for your issue.
I have check the guide one more time and found out that it ok - please take a loot to the [Publishing to NuGet feed](https://www.appveyor.com/docs/deployment/nuget)
